CREATE TABLE RecapOfTheDay (
	id BIGINT NOT NULL AUTO_INCREMENT,
	agent VARCHAR(255) NOT NULL,
	type VARCHAR(255) NOT NULL,
	center VARCHAR(255) NOT NULL,
	count VARCHAR(255) NOT NULL,
	PRIMARY KEY(id)
);